#!/usr/bin/env python3
"""Generate archive/<date>-v<version>.md for each patch JSON — GitHub-native readable, AI-scrapable."""
import json, os, sys

ROOT = os.path.join(os.path.dirname(os.path.abspath(__file__)), '..')
PATCHES_DIR = os.path.join(ROOT, 'patches')
ARCHIVE_DIR = os.path.join(ROOT, 'archive')

SECTION_LABEL = {
    'added':    ('Added', '🟢'),
    'changed':  ('Changed', '🟡'),
    'fixed':    ('Fixed', '🔵'),
    'removed':  ('Removed', '🔴'),
    'deprecated': ('Deprecated', '🟠'),
    'security': ('Security', '🔒'),
}

def patch_to_md(data: dict) -> str:
    version = data.get('version', 'unknown')
    title = data.get('title', f'v{version}')
    date = data.get('date', '')
    steam_url = data.get('steam_url', '')

    lines = [
        f'# SpiritVale v{version} — {title}',
        '',
        f'**Date**: {date}  ',
        f'**Version**: {version}  ',
    ]
    if steam_url:
        lines.append(f'**Steam**: [{steam_url}]({steam_url})  ')
    lines += ['', '---', '']

    for key, (label, emoji) in SECTION_LABEL.items():
        entries = data.get(key, [])
        if not entries:
            continue
        lines.append(f'## {emoji} {label}')
        lines.append('')
        for item in entries:
            lines.append(f'- {item}')
        lines.append('')

    lines += [
        '---',
        '',
        '*Generated by [spiritvale-site](https://spiritvale.tama.sh/) — machine-readable patch archive*',
    ]
    return '\n'.join(lines) + '\n'

os.makedirs(ARCHIVE_DIR, exist_ok=True)

written = 0
for fname in sorted(os.listdir(PATCHES_DIR)):
    if not fname.startswith('v') or not fname.endswith('.json'):
        continue
    path = os.path.join(PATCHES_DIR, fname)
    with open(path) as f:
        data = json.load(f)

    version = data.get('version', fname[1:-5])
    date = data.get('date', '0000-00-00')
    out_name = f'{date}-v{version}.md'
    out_path = os.path.join(ARCHIVE_DIR, out_name)

    with open(out_path, 'w') as f:
        f.write(patch_to_md(data))
    written += 1

print(f'mirror: wrote {written} markdown files to archive/', file=sys.stderr)
